Kirill-Filonchuk/pet_team02

src/components/Header/Header.jsx
src/components/Header/Header.style.js
src/components/Logo/Logo.jsx
src/components/Navigation/AuthNav.jsx
src/components/Navigation/Navigation.jsx
src/components/SharedLayout/SharedLayout.js
src/pages/HomePage/HomePage.jsx
src/pages/LoginPage/LoginPage.jsx
src/pages/NewsPage/NewsPage.jsx
src/pages/OurFriendsPage/OurFriendsPage.jsx
src/pages/RegisterPage/RegisterPage.jsx
src/router.js

добавила общую навигацию, заглушки на страницы навигации. бургер-меню для моб и планш версии еще не готово(завтра доработаю)

headers navigation added

---

src/index.css
src/index.js

fix normalize, reconnect the correct import and add fonts

fix normalize and fonts

---

src/index.css
src/theme.js

update theme and fonts

---

src/components/Header/Header.jsx
src/components/Header/Header.style.js
src/components/Logo/Logo.jsx
src/components/Navigation/AuthNav.jsx
src/components/Navigation/Navigation.jsx
src/index.css
src/pages/HomePage/HomePage.jsx
src/theme.js

добавила стили на хедер(десктоп недоработан) и закрытие меню по клику на позицию в меню.

added some style

---

src/components/Header/Header.jsx
src/components/Header/Header.styled.js
src/components/Logo/Logo.jsx
src/components/Navigation/Navigation.jsx

добавила мини анимацию при ховере в одном стиле на всё: на лого, на навигацию на десктопе и на навигацию в бургер меню. По поводу выпрыгивающей буквы, пробовала, но мне как-то не то, но еще попробую.

added scale on links and logo

---

src/components/App/App.jsx
src/components/Notices/Notices.jsx
src/index.js

Return App back and set Router Provider there

The Return Of The King (App)

---

src/components/Modal/Modal.jsx
src/components/Modal/Modal.styled.js
src/components/UIKit/EscButton/EscButton.styled.js

fix reusable modal styles and add escbutton

fix reusable modal styles and add escbutton

---

src/components/Helpers/Spinner/Spinner.styled.js
src/components/Logo/Logo.jsx
src/components/SharedLayout/SharedLayout.js

logo-animation added

---

src/components/Account/Account.styled.js
src/components/Header/Header.styled.js

пофиксила ширину контейнера на десктопе

header container desctop fix

---

src/components/ModalNotice/ModalNotice.jsx
src/components/ModalNotice/ModalNotice.styled.js
src/components/ModalNotice/PetLearnMore.jsx
src/components/ModalNotice/PetLearnMore.styled.js
src/components/ModalNotice/index.js

add modal for notice

---

src/components/SharedLayout/SharedLayout.js

добавила спиннер в sharedLayout ,чтоб не забыть(пока без стилей)

added spinner on sharedlayout

---

src/components/Header/Header.jsx
src/components/Header/Header.styled.js
src/components/Logo/Logo.jsx

fixed style

---

src/components/ModalNotice/ModalNotice.jsx
src/components/ModalNotice/PetLearnMore.jsx
src/components/ModalNotice/PetLearnMore.styled.js

fixed styles

---

src/components/NewsList/NewsList.jsx
src/components/NewsSearch/NewsSearch.jsx

After removing the query from the search field, the entire news list opens.

Bug fix/news

---

src/components/ModalNotice/ModalNotice.jsx
src/components/ModalNotice/PetLearnMore.jsx
src/components/ModalNotice/PetLearnMore.styled.js
src/components/NoticesCard/NoticesCard.jsx

add to favorite works

---

src/components/App/App.jsx
src/components/UserData/UserData.jsx
src/components/UserData/UserData.styled.jsx
src/components/UserDataItem/UserDataItem.jsx
src/components/UserDataItem/UserDataItem.styled.jsx
src/pages/UserPage/UserPage.jsx
src/redux/auth/slice.js

хай, чекни по свободе плз
в АПП закоментил намерено при рефреше сообщение "Refreshing user..."

User data/fixstyle

---

src/components/Account/Account.styled.js
src/components/Header/Header.styled.js

пофиксила стили хедера ,когда высвечивается кнопка аккаунт (было не соответствие с макетом)

fixed headers styles

---

src/components/ModalNotice/PetLearnMore.jsx
src/components/ModalNotice/PetLearnMore.styled.js

fix styles

---

src/components/Account/Account.js
src/components/Account/Account.styled.js
src/components/Header/Header.jsx
src/components/Header/Header.styled.js
src/components/Logo/Logo.jsx
src/components/Logo/Logo.styled.js
src/components/Navigation/Navigation.styled.js

пофиксила баги по замечаниям от тестировщиков

Logo no translate

---

src/components/UserData/UserData.jsx
src/components/UserData/UserData.styled.jsx
src/components/UserDataItem/UserDataItem.jsx
src/pages/UserPage/UserPage.jsx
src/pages/UserPage/UserPage.styled.jsx
src/redux/auth/slice.js

User data/add some feature

---

src/components/Header/Header.styled.js
src/components/Helpers/Spinner/Spinner.styled.js
src/components/SharedLayout/SharedLayout.js
src/components/SharedLayout/SharedLayout.styled.js

пофиксила прыжки кнопки бургер меню на мобилке и поставила стили на sharedLayout в sharedLayout.styled.js

fixed burger button and sharedlayouts style

---

src/components/FormValidation/FormValidation.jsx
src/components/UserDataItem/UserDataItem.jsx

Auth adaptive

---

src/components/NewsCard/NewsCard.styled.js
src/components/NewsList/NewsList.jsx
src/components/NewsList/NewsList.styled.js

Add hover on "Read more", IconCat if missing news and corrects toastyfy

Bug fix/read more toastyfy
